### PR TITLE
Support day boundaries

### PR DESCRIPTION
**Pull request by Gottox**
this commit adds support for alarm hours like 8am till 1am. It does this
by adding one day to the end time if the plugin detects that the end
time is earlier than the start time.

### CODE REVIEW

**Comment by Gottox** [comment]
Please note, that I'm currently waiting for a print to finish, so this is currently untested. :smiley:

**Comment by techfreek** [comment]
This looks great! If you don't mind, I'd like to try this out on my printer first, but I'm currently waiting for a new thermistor so I can print again. 
Thank you for this PR and the other one!

**Comment by Gottox** [comment]
Thanks for the handy plugin :+1:

**Comment by techfreek** [comment]
I'll merge this and your other pr into the development branch and do some testing.

**Pull request merged**
